name: Scrape BMW aktuell

on:
  schedule:
    - cron: "30 18 * * *" # every day at 18:30
  workflow_dispatch:

jobs:
  scrape_bmw_aktuell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - run: pip install requests bs4 pandas datetime
    - name: Run scraper for BMW aktuell
      run: python scrape_bmw_aktuell.py
    - name: Add and commit	
      run: |-	
        git add .	
        git config user.name "Automated"	
        git config user.email "actions@users.noreply.github.com"	
        timestamp=$(date -u)
        git commit -m "Latest data from BMW aktuell: ${timestamp}" || exit 0 	
    - name: Push	
      run: git push
